language: node_js
node_js:
  - lts/*
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.63.2/hugo_0.63.2_Linux-64bit.deb
  - sudo dpkg -i hugo_0.63.2_Linux-64bit.deb
  - npm install -g firebase-tools
script:
  - hugo
after_script:
  - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT
