baseURL = "https://rafaelmatsumoto.dev/"
languageCode = "en-us"
title = "Rafael M."
theme = "hugo-ink"
paginate = 5

copyright = "©"

[markup]
  [markup.highlight]
    style = "emacs"
  [markup.goldmark.renderer]
	unsafe= true

[params]
	subtitle = "Uma coleção de posts sobre tecnologia"

	avatar = "https://s.gravatar.com/avatar/132c621a9e8d6d2e6b95a4d58d4812ec"

	featherIconsCDN = true

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/rafaelmatsumoto/"

[[params.social]]
name = "Goodreads"
icon = "book"
url = "https://www.goodreads.com/user/show/79981049-rafael-stein"

