baseURL = "https://rafaelmatsumoto.com/"
languageCode = "en-us"
title = "Rafael Matsumoto"
theme = "hugo-ink"
disqusShortname = ""
disableKinds = ["googleanalytics"]
[pagination]
  pagerSize = 5

copyright = "© 2026 Rafael Matsumoto"

[markup]
  [markup.highlight]
    style = "emacs"
  [markup.goldmark.renderer]
	unsafe= true

[params]
	subtitle = "Digital garden"
	description = "Digital garden of Rafael Matsumoto - software developer sharing insights on backend engineering, infrastructure, and technology."
disqusShortname = "myblog"

	avatar = "https://s.gravatar.com/avatar/132c621a9e8d6d2e6b95a4d58d4812ec"

	featherIconsCDN = true

    # favicon = "/static/img/favicon-16x16.png"

    favicon = "https://s.gravatar.com/avatar/132c621a9e8d6d2e6b95a4d58d4812ec"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "TIL"
url = "/til/"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/rafaelmatsumoto/"

[[params.social]]
name = "Goodreads"
icon = "book"
url = "https://www.goodreads.com/rafaelmatsumoto"

[deployment]

[[deployment.targets]]
name = "production"

URL = "s3://rafaelmatsumoto.com?region=us-west-2"
